title: Amy Nicholson
description: Amy Nicholson's personal website
baseurl: ""
url: https://amy-nicholson.co.uk

theme: cvless

# site settings
taglong: "Technical product owner<br/>and problem solver"
tagshort: "" 

# author settings
author:
  name: Amy Nicholson
  email: hello@amy-nicholson.co.uk
photo: assets/files/avatar.jpeg

# social media links
social:
  linkedin: amy-nicholson-b48b747a
  github: amy-nicholson

permalink: pretty
exclude:
  - README.md

plugins:
  - jekyll-target-blank
  - jemoji
