baseURL = 'https://example.org/'
languageCode = 'en-gb'
title = 'Amy Gormley'
theme = 'github.com/derme302/triple-hyde'

enableEmoji = true

[params]
author = "Amy Gormley"
since = 2024
authorimage = "/img/avatar.jpeg"
mainSections = [ "About" ]
postNavigation = false

[params.social]
github = "amygormley"
linkedin = "amy-gormley-b48b747a"

[[menu.main]]
name = "About"
weight = 100
identifier = "about"
url = "/about/"
[[menu.main]]
name = "Experience"
identifier = "experience"
weight = 200
url = "/experience/"
[[menu.main]]
name = "Skills"
identifier = "skills"
weight = 250
url = "/skills/"
[[menu.main]]
name = "Contact"
identifier = "contact"
weight = 300
url = "/contact/"
